//同步方法
export default {
    //修改登录状态
    changeLogin(state,isLogin){
        state.isLogin=isLogin
    },
    //修改token状态
    changeToken(state,token){
        state.token=token
    },
    //修改Loading状态
    changeLoading(state,loading){
        state.loading=loading
    },
    //修改组织状态
    changeOrganization(state,organization){
        state.organizationStatus=organization
    },
    changeOrganizationText(state,organization){
        state.organizationText=organization
    }
}